# .circleci/config.yml file
version: 2.1

jobs:
  build: # job name
    docker: # executor type
      - image: cimg/base:current # Docker image that installs Docker and has Git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: echo "No need to install anything. \n Just build and push the Docker image."
      - run:
          name: Build and push Docker image
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            docker build -t datacamp553/udagram-api-feed:latest  ./udagram-api-feed 
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push datacamp553/udagram-api-feed:latest
            echo "udagram-api-feed pushed"
            docker build -t datacamp553/udagram-api-user:latest  ./udagram-api-user 
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push datacamp553/udagram-api-user:latest
            echo "udagram-api-user pushed"
            docker build -t datacamp553/udagram-frontend:latest  ./udagram-frontend
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push datacamp553/udagram-frontend:latest
            echo "udagram-frontend pushed"
            docker build -t datacamp553/udagram-reverseproxy:latest  ./udagram-reverseproxy
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push datacamp553/udagram-reverseproxy:latest
            echo "udagram-reverseproxy pushed"
